### ISSUE TITLE
ListNestedAttributes crashes when an attributes contains an Int64 type.

### ISSUE THREAD

**Issue by mad-it** [hashicorp/terraform-plugin-framework#278]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.6.0
```

### Relevant provider source code

```go
package provider

import (
	"context"
	"math/rand"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

type bugType struct{}

func (t bugType) GetSchema(ctx context.Context) (tfsdk.Schema, diag.Diagnostics) {
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
			"id": {
				Computed: true,
				Type:     types.Int64Type,
				PlanModifiers: tfsdk.AttributePlanModifiers{
					tfsdk.UseStateForUnknown(),
				},
			},
			"name": {
				Optional: true,
				Type:     types.StringType,
			},
			"list": {
				Required: true,
				Attributes: tfsdk.ListNestedAttributes(
					map[string]tfsdk.Attribute{
						"number": {
							Required: true,
							Type:     types.Int64Type,
						},
					},
					tfsdk.ListNestedAttributesOptions{},
				),
			},
		},
	}, nil
}

func (t bugType) NewResource(ctx context.Context, in tfsdk.Provider) (tfsdk.Resource, diag.Diagnostics) {
	provider, diags := convertProviderType(in)

	return bug{
		provider: provider,
	}, diags
}

type bug struct {
	provider provider
}

type bugProviderTypeData struct {
	ID   types.Int64   `tfsdk:"id"`
	Name types.String  `tfsdk:"name"`
	List []bugTypeData `tfsdk:"list"`
}

type bugTypeData struct {
	Number types.Int64 `tfsdk:"number"`
}

func (r bug) Create(ctx context.Context, req tfsdk.CreateResourceRequest, resp *tfsdk.CreateResourceResponse) {
	var data bugProviderTypeData

	diags := req.Plan.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.Int64{Value: rand.Int63()}

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r bug) Read(ctx context.Context, req tfsdk.ReadResourceRequest, resp *tfsdk.ReadResourceResponse) {
	var data bugProviderTypeData

	diags := req.State.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r bug) Update(ctx context.Context, req tfsdk.UpdateResourceRequest, resp *tfsdk.UpdateResourceResponse) {
	var data bugProviderTypeData

	diags := req.Plan.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &data)
	resp.Diagnostics.Append(diags...)
}

func (r bug) Delete(ctx context.Context, req tfsdk.DeleteResourceRequest, resp *tfsdk.DeleteResourceResponse) {
	var data bugProviderTypeData

	diags := req.State.Get(ctx, &data)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.State.RemoveResource(ctx)
}

func (r bug) ImportState(ctx context.Context, req tfsdk.ImportResourceStateRequest, resp *tfsdk.ImportResourceStateResponse) {
	tfsdk.ResourceImportStatePassthroughID(ctx, tftypes.NewAttributePath().WithAttributeName("id"), req, resp)
}

```

### Terraform Configuration Files

First:
```hcl
resource "provider_bug" "test" {
  name = "test-bug"
  list = [
    {
      number = 1
    },
    {
      number = 2
    }
  ]
}
```

Second:
```hcl
resource "provider_bug" "test" {
  name = "test-bug"
  list = [
    {
      number = 1
    },
    {
      number = 2
    },
    {
      number = 3
    }
  ]
}
```

### Debug Output

```
Stack trace from the terraform-provider-bug plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5a284a]

goroutine 40 [running]:
github.com/hashicorp/terraform-plugin-framework/types.int64Validate({0xc0001ab5f0, 0x7fa41812a2b8}, {{0x0, 0x0}, {0x0, 0x0}}, 0x40b72d)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/types/int64.go:16 +0x8a
github.com/hashicorp/terraform-plugin-framework/types.primitive.Validate(0x80, {0xbc4478, 0xc000209480}, {{0x0, 0x0}, {0x0, 0x0}}, 0xfab0f8)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/types/primitive.go:121 +0xa5
github.com/hashicorp/terraform-plugin-framework/tfsdk.State.getAttributeValue({{{0xbcd7c0, 0xc000275b90}, {0xa18060, 0xc000274b10}}, {0xc0002615f0, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...}}, ...)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/tfsdk/state.go:95 +0x297
github.com/hashicorp/terraform-plugin-framework/tfsdk.Attribute.modifyPlan({{0xbc9818, 0xfab0f8}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x1, 0x0, ...}, ...)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/tfsdk/attribute.go:498 +0x168
github.com/hashicorp/terraform-plugin-framework/tfsdk.Attribute.modifyPlan({{0x0, 0x0}, {0xbca938, 0xc000261620}, {0x0, 0x0}, {0x0, 0x0}, 0x1, 0x0, ...}, ...)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/tfsdk/attribute.go:576 +0x1968
github.com/hashicorp/terraform-plugin-framework/tfsdk.Schema.modifyPlan({_, _, _, {_, _}, {_, _}, {_, _}}, {0xbc4478, ...}, ...)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/tfsdk/schema.go:316 +0x250
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).planResourceChange(0xc0003cdb00, {0xbc4478, 0xc000209480}, 0xc000214f00, 0xc00050b640)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/tfsdk/serve.go:917 +0xece
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).PlanResourceChange(0xbc4478, {0xbc4478, 0xc0002093c0}, 0x5)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.6.0/tfsdk/serve.go:738 +0x90
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).PlanResourceChange(0xc0002a1220, {0xbc4520, 0xc000260e10}, 0xc0002470a0)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov6/tf6server/server.go:777 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_PlanResourceChange_Handler({0xaaebc0, 0xc0002a1220}, {0xbc4520, 0xc000260e10}, 0xc00022ad80, 0x0)
        /home/user/Projects/Go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00036c8c0, {0xbd02f8, 0xc000115ba0}, 0xc00022d200, 0xc0003cdc50, 0x100eac8, 0x0)
        /home/user/Projects/Go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00036c8c0, {0xbd02f8, 0xc000115ba0}, 0xc00022d200, 0x0)
        /home/user/Projects/Go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/user/Projects/Go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/user/Projects/Go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x294
```

### Expected Behavior

The plugin should not crash when an additional item is added.

### Actual Behavior

Its crashing

### Steps to Reproduce

1. Run terraform apply with a list of one or more items
2. Add an additional item to the list
3. Run terraform apply once again and the plugin crashes.

One thing to note: when removing an item from the list, it works fine.

**Comment by bflad** [comment]
Hi @mad-it 👋  Thank you very much for the detailed bug report and apologies you ran into trouble here. This is certainly unexpected behavior in the framework and we will try to investigate the root cause in the coming days. At first glance this might be due to some unexpected type handling when attempting to retrieve a (correctly) missing state value at a path that corresponds to the new planned value.

**Comment by mad-it** [comment]
Yep, this seems to have solved the issue 👍🏼
