### ISSUE TITLE
Missing/Null Object During State Setting Causes Panic With Missing Attribute Types

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform-plugin-framework#566]
### Module version

```
v0.16.0
```

### Relevant provider source code

```go
	return tfsdk.Schema{
		Attributes: map[string]tfsdk.Attribute{
        "precheck": tfsdk.Attribute{
                Optional:            true,
                Attributes: tfsdk.SingleNestedAttributes(map[string]tfsdk.Attribute{
                    "status_locator": {
                        Required:            true,
                        Type:                types.StringType,
                    },
                    "status": {
                        Required:            true,
                        Attributes: tfsdk.SingleNestedAttributes(map[string]tfsdk.Attribute{
                            "success": {
                                Required:            true,
                                Type:                types.StringType,
                            },
                            "pending": {
                                Optional:            true,
                                Type:                types.ListType{ElemType: types.StringType},
                            },
                        }),
                    },
                    "path": {
                        Type:                types.StringType,
                        Required:            pathIsRequired,
                        Optional:            !pathIsRequired,
                    },
                    "query": {
                        Type:                types.MapType{ElemType: types.ListType{ElemType: types.StringType}},
                        Optional:            true,
                    },
                    "default_delay_sec": {
                        Optional:            true,
                        Type:                types.Int64Type,
                    },
                }),
            }
		},
	}, nil

```

### Terraform Configuration Files

```hcl
func (d jsonServerData) dsBasic() string {
	return fmt.Sprintf(`
provider "restful" {
  base_url = %q
}

resource "restful_resource" "test" {
  path = "/posts"
  body = jsonencode({
  	foo = "bar"
})
  read_path = "$(path)/$(body.id)"
}

data "restful_resource" "test" {
  id = restful_resource.test.id
}
`, d.url)

}

```

### Expected Behavior

Apply works.

### Actual Behavior

Crashed with following error:

```shell
terraform-provider-restful on  precheck via 🐹 v1.19.3 took 23s
💤  TF_ACC=1 go test -v -timeout=20h ./internal/provider -run=TestDataSource_JSONServer_Basic
=== RUN   TestDataSource_JSONServer_Basic
panic: AttributeName("precheck"): can't use tftypes.Object[] as tftypes.Object["default_delay_sec":tftypes.Number, "path":tftypes.String, "query":tftypes.Map[tftypes.List[tftypes.String]], "status":tftypes.Object["pending":tftypes.List[tftypes.String], "success":tftypes.String], "status_locator":tftypes.String]

goroutine 240 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.NewValue(...)
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.1/tftypes/value.go:273
github.com/hashicorp/terraform-plugin-framework/internal/reflect.FromStruct({0x1053d80, 0xc0004cc3f0}, {0x10584b0?, 0xc00014da40?}, {0xe59060?, 0xc0004d5040?, 0x0?}, {{0x1664af8, 0x0, 0x0}})
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/reflect/struct.go:207 +0xac5
github.com/hashicorp/terraform-plugin-framework/internal/reflect.FromValue({0x1053d80, 0xc0004cc3f0}, {0x1056e80?, 0xc00014da40}, {0xe59060, 0xc0004d5040}, {{0x1664af8?, 0x9?, 0x203000?}})
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/reflect/outof.go:54 +0x95b
github.com/hashicorp/terraform-plugin-framework/internal/fwschemadata.(*Data).Set(0xc0000e09e8, {0x1053d80, 0xc0004cc3f0}, {0xe59060, 0xc0004d5040})
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/fwschemadata/data_set.go:15 +0x9a
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*State).Set(0xc00014e900, {0x1053d80, 0xc0004cc3f0}, {0xe59060, 0xc0004d5040})
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.16.0/tfsdk/state.go:59 +0x1c6
github.com/magodo/terraform-provider-restful/internal/provider.(*DataSource).Read(0xc00060e1f8, {0x1053d80, 0xc0004cc3f0}, {{{{0x1058610, 0xc0004ccfc0}, {0xd9fae0, 0xc0004ccb10}}, {0xc000238db0, 0x0, 0x0, ...}}, ...}, ...)
        /home/magodo/github/terraform-provider-restful/internal/provider/data_source.go:161 +0x7ce
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc000318420, {0x1053d80, 0xc0004cc3f0}, 0xc0004cc420, 0xc0000e1620)
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/fwserver/server_readdatasource.go:75 +0x638
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc000318420, {0x1053d80?, 0xc0004cc300?}, 0xc00069d480)
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v0.16.0/internal/proto6server/server_readdatasource.go:52 +0x28d
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc000694780, {0x1053d80?, 0xc000687b60?}, 0xc000278870)
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov6/tf6server/server.go:656 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0xe7b220?, 0xc000694780}, {0x1053d80, 0xc000687b60}, 0xc0002303f0, 0x0)
        /home/magodo/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000506780, {0x10588f8, 0xc00047c9c0}, 0xc000288000, 0xc000341b90, 0x16258d0, 0x0)
        /home/magodo/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000506780, {0x10588f8, 0xc00047c9c0}, 0xc000288000, 0x0)
        /home/magodo/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/magodo/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/magodo/go/pkg/mod/google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
FAIL    github.com/magodo/terraform-provider-restful/internal/provider  0.119s
FAIL
```

### Steps to Reproduce

1. Checkout https://github.com/magodo/terraform-provider-restful/pull/26/commits/da65e83e37e0d18dc84d60a9decb8f8247e298c8
2. Starts a local jsonserver
3. Run `TF_ACC=1 go test -v -timeout=20h ./internal/provider -run=TestDataSource_JSONServer_Basic
`

## Reference

https://github.com/magodo/terraform-provider-restful/pull/26

**Comment by bflad** [comment]
Hi @magodo 👋 Thank you for raising this and sorry you ran into trouble here.

A quick fix for your situation would be to ensure that the `resp.State.Set()` call in your code is copying the new `Precheck` field from the configuration data, e.g.

```go
	state := dataSourceData{
		ID:       config.ID,
		Query:    config.Query,
		Header:   config.Header,
		Selector: config.Selector,
		Precheck: config,Precheck,
		Output:   types.StringValue(string(b)),
	}
	diags = resp.State.Set(ctx, state)
```

This should ensure that the reflection logic is receiving a fully baked `types.Object` with attribute types and prevent the underlying panic. Another methodology that could be applied in this code would be to only set additional information on top of the existing configuration data since Terraform requires the data to be symmetrical, e.g.

```go
config.Output = types.StringValue(string(b))
diags = resp.State.Set(ctx, config)
```

---

To have the framework prevent the panic in this situation, it would likely require the type reflection logic to have the schema information available so it can either populate the missing type information or to compare type information for raising an error. Populating the missing type information could potentially lead to a Terraform-defined error about the mismatch between configuration and state, but that seems better than an unexpected and admittedly harder to troubleshoot panic.

**Comment by magodo** [comment]
@bflad Thank you for the reply, it is very helpful! This indeed is a bug in my provider code, whilst shall we keep this issue open to keep track of providing a more user friendly diag message?

**Comment by bflad** [comment]
@magodo sounds good 👍 We should certainly try to present a normal error over the panic.

**Comment by bflad** [comment]
Related: https://github.com/hashicorp/terraform-plugin-framework-timeouts/issues/46

I think I have a good enough grasp on the affected code to at least convert the panic to an error.
