### ISSUE TITLE
Panic when using object default planmodifier

### ISSUE THREAD

**Issue by iwarapter** [hashicorp/terraform-plugin-framework#582]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v1.0.0
```

### Relevant provider source code

https://github.com/iwarapter/terraform-provider-corner/commit/9e8992d9de76af7dbb89997343c1a7f7b3b17ea7

### Terraform Configuration Files

See unit tests in reproducer

### Expected Behavior

Im trying to use an `planmodifier.Object` to specify the default value for a `schema.SingleNestedAttribute` however it fails and panics, i'm not sure if I have a bug with my implementation or the framework. I have defaults for other complex types (list, set) all working correctly. I have lifted the relevant provider code and added it to the corner provider as a simple reproducer.

This is ultimately because https://github.com/hashicorp/terraform-plugin-framework/blob/707c9ca36898a421366106f41ed76cc577802f78/internal/fwserver/attribute_plan_modification.go#L1702

Is nil

### Actual Behavior
```
go test ./internal/framework6provider/... -v                  
=== RUN   TestAccFrameworkResourceUser
panic: assignment to entry in nil map

goroutine 107 [running]:
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.NestedAttributeObjectPlanModify({_, _}, {_, _}, {{{0x140005f7230, 0x1, 0x1}}, {0x0, {0x0, 0x0, ...}}, ...}, ...)
        /code/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.0.0/internal/fwserver/attribute_plan_modification.go:1748 +0x510
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.AttributeModifyPlan({_, _}, {_, _}, {{{0x140005f7230, 0x1, 0x1}}, {0x0, {0x0, 0x0, ...}}, ...}, ...)
        /code/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.0.0/internal/fwserver/attribute_plan_modification.go:425 +0x1dac
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.SchemaModifyPlan({0x104da2900, 0x140005df830}, {0x104da8508, 0x1400018e4b0}, {{{{0x104da7140, 0x140005e65a0}, {0x104c8e340, 0x140005dfef0}}, {0x104da8508, 0x1400018e4b0}}, ...}, ...)
        /code/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.0.0/internal/fwserver/schema_plan_modification.go:120 +0x4f0
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).PlanResourceChange(0x140002a7760, {0x104da2900, 0x140005df830}, 0x1400014cf00, 0x14000333488)
        /code/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.0.0/internal/fwserver/server_planresourcechange.go:201 +0x9e8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).PlanResourceChange(0x140002a7760, {0x104da2900?, 0x140005df740?}, 0x1400014ceb0)
        /code/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.0.0/internal/proto6server/server_planresourcechange.go:52 +0x1a8
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).PlanResourceChange(0x1400030fc20, {0x104da2900?, 0x140005def60?}, 0x14000480770)
        /code/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/tf6server/server.go:781 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_PlanResourceChange_Handler({0x104d679c0?, 0x1400030fc20}, {0x104da2900, 0x140005def60}, 0x14000480690, 0x0)
        /code/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140003201e0, {0x104da7480, 0x140004bcb60}, 0x140005e1560, 0x1400048a990, 0x1053147c8, 0x0)
        /code/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x140003201e0, {0x104da7480, 0x140004bcb60}, 0x140005e1560, 0x0)
        /code/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /code/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /code/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x290
FAIL    github.com/hashicorp/terraform-provider-corner/internal/framework6provider      0.232s
FAIL

```

### Steps to Reproduce

```
go test ./internal/framework6provider/... -v   
```

**Comment by bflad** [comment]
Hi again @iwarapter! 👋 Thank you for raising this. I think we'll need to dive a little more into this, but at first glance, I'm not seeing anything wrong on your side. Does the code work without the plan modifier?

**Comment by iwarapter** [comment]
hey @bflad so without the default plan modifier I get a provider failure and the planned isnt whats saved:
```hcl
resource "pingfederate_oauth_client" "example" {
  client_id   = "example"
  name        = "example"
  grant_types = ["CLIENT_CREDENTIALS"]

  client_auth = {
    secret = "super_top_secret"
    type   = "SECRET"
  }
}
```
```
pingfederate_oauth_client.example: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to pingfederate_oauth_client.example, provider "provider[\"registry.terraform.io/iwarapter/pingfederate\"]" produced an unexpected new value: .oidc_policy: was null, but now
│ cty.ObjectVal(map[string]cty.Value{"grant_access_session_revocation_api":cty.False, "grant_access_session_session_management_api":cty.False, "id_token_content_encryption_algorithm":cty.NullVal(cty.String),
│ "id_token_encryption_algorithm":cty.NullVal(cty.String), "id_token_signing_algorithm":cty.NullVal(cty.String), "logout_uris":cty.NullVal(cty.List(cty.String)), "pairwise_identifier_user_type":cty.False,
│ "ping_access_logout_capable":cty.False, "policy_group":cty.NullVal(cty.String), "sector_identifier_uri":cty.NullVal(cty.String)}).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
Manually defining the defaults in config:
```hcl
resource "pingfederate_oauth_client" "example" {
  client_id   = "example"
  name        = "example"
  grant_types = ["CLIENT_CREDENTIALS"]

  client_auth = {
    secret = "super_top_secret"
    type   = "SECRET"
  }
  oidc_policy = {
    grant_access_session_revocation_api         = false
    ping_access_logout_capable                  = false
  }
}
```
```

pingfederate_oauth_client.example: Creating...
pingfederate_oauth_client.example: Creation complete after 0s [id=example]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```
Which is what I would expect to see if the provider isn't defining an expected

**Comment by bflad** [comment]
Thanks for the followup. My apologies that I wasn't clear in my intention of asking whether "the code" works -- I was intending to ask whether the provider code panics without the plan modifier. I believe you answered that question where the provider code is able to execute, however the mismatched data between the plan and apply due to the API's response, does cause the Terraform error. We'll certainly want to get the framework able to accept the plan modifier in this case without the panic and therefore without the Terraform error.

It's not immediately clear to me why the framework's automatic `Computed` attribute null configuration value -> unknown plan value is not happening in this case for the object itself, but you may be able to workaround the current situation by forcibly marking the object as unknown via a plan modifier:

```go
// untested
func (m objectDefaultModifier) PlanModifyObject(ctx context.Context, req planmodifier.ObjectRequest, resp *planmodifier.ObjectResponse) {
	// If the attribute configuration is not null, we are done here
	if !req.ConfigValue.IsNull() {
		return
	}

	resp.PlanValue = types.ObjectUnknown(req.PlanValue.AttributeTypes(ctx))
}
```

You can verify the plan is working or not working as expected with the acceptance testing run with `TF_LOG=TRACE` and finding the log entry which outputs the "human readable" plan similar to as if Terraform was run from the CLI. This unknown setting should hopefully prevent the Terraform error though.

By the way, using the `req.PlanValue.AttributeTypes()` approach should help remove the need to manually specify the attribute types in the call to your plan modifier.

I'll hopefully have some time early next week to look into this in-depth.

**Comment by iwarapter** [comment]
Hi @bflad,

> By the way, using the req.PlanValue.AttributeTypes() approach should help remove the need to manually specify the attribute types in the call to your plan modifier.

```golang
// PlanModifyObject updates the planned value with the default if its not null
func (m objectDefaultModifier) PlanModifyObject(ctx context.Context, req planmodifier.ObjectRequest, resp *planmodifier.ObjectResponse) {
	// If the attribute configuration is not null, we are done here
	if !req.ConfigValue.IsNull() {
		return
	}

	// If the attribute plan is "known" and "not null", then a previous plan modifier in the sequence
	// has already been applied, and we don't want to interfere.
	if !req.PlanValue.IsUnknown() && !req.PlanValue.IsNull() {
		return
	}
	resp.PlanValue, resp.Diagnostics = types.ObjectValue(req.PlanValue.AttributeTypes(ctx), m.Elements)
}
```

Thanks for the `req.PlanValue.AttributeTypes()` tip, much nicer. 

I was able to get this working with a quick nil check on the attribute_plan_modifer:
```
diff --git a/vendor/github.com/hashicorp/terraform-plugin-framework/internal/fwserver/attribute_plan_modification.go b/vendor/github.com/hashicorp/terraform-plugin-framework/internal/fwserver/attribute_plan_modification.go
index 1afbf2c..3963de5 100644
--- a/vendor/github.com/hashicorp/terraform-plugin-framework/internal/fwserver/attribute_plan_modification.go
+++ b/vendor/github.com/hashicorp/terraform-plugin-framework/internal/fwserver/attribute_plan_modification.go
@@ -1700,6 +1700,9 @@ func NestedAttributeObjectPlanModify(ctx context.Context, o fwschema.NestedAttri
        }
 
        newPlanValueAttributes := req.PlanValue.Attributes()
+       if newPlanValueAttributes == nil {
+               newPlanValueAttributes = map[string]attr.Value{}
+       }
 
        for nestedName, nestedAttr := range o.GetAttributes() {
                nestedAttrConfig, diags := objectAttributeValue(ctx, req.ConfigValue, nestedName, fwschemadata.DataDescriptionConfiguration)
```

So with my updated default object plan modifier:
```golang
"oidc_policy": schema.SingleNestedAttribute{
				Description: `Open ID Connect Policy settings.  This is included in the message only when OIDC is enabled.`,
				Optional:    true,
				Computed:    true,
				Attributes:  singleClientOIDCPolicy(),
				PlanModifiers: []planmodifier.Object{
					defaults.DefaultObject(map[string]attr.Value{
						"grant_access_session_revocation_api":         types.BoolValue(false),
						"grant_access_session_session_management_api": types.BoolValue(false),
						"id_token_content_encryption_algorithm":       types.StringValue("RS256"),
						"sector_identifier_uri":                       types.StringNull(),
						"policy_group":                                types.StringNull(),
						"pairwise_identifier_user_type":               types.BoolNull(),
						"ping_access_logout_capable":                  types.BoolNull(),
						"id_token_encryption_algorithm":               types.StringNull(),
						"logout_uris":                                 types.ListUnknown(types.StringType),
						"id_token_signing_algorithm":                  types.StringNull(),
					}),
				},
			},
```

If you are happy with my workaround on the attribute_plan_modifier, happy to raise a PR for this.
