### ISSUE TITLE
nil pointer exception when testing provider-defined functions

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-plugin-framework#928]
When testing provider-defined functions in a way that requires preparing a function.RunResponse input to the function under test, like this:

https://github.com/hashicorp/terraform-plugin-framework/blob/3c7a391644c7f8b8d18d8cb61153f937c80893ad/website/docs/plugin/framework/functions/testing.mdx#L221

I get a nil pointer exception like this:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x100474da0]

goroutine 8 [running]:
testing.tRunner.func1.2({0x103963300, 0x105921220})
        /Users/sarahfrench/sdk/go1.20.12/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
        /Users/sarahfrench/sdk/go1.20.12/src/testing/testing.go:1529 +0x384
panic({0x103963300, 0x105921220})
        /Users/sarahfrench/sdk/go1.20.12/src/runtime/panic.go:884 +0x204
github.com/hashicorp/terraform-plugin-framework/function.(*ResultData).Set(0x14000c0df48, {0x103f76c68, 0x14000190018}, {0x103719700, 0x140005cf4d0})
        /Users/sarahfrench/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.5.0/function/result_data.go:38 +0x40
github.com/hashicorp/terraform-provider-google/google/functions.ProjectFromIdFunction.Run({}, {0x103f76c68, 0x14000190018}, {{{0x140005cf320?, 0x105961680?, 0x14000bb3f18?}}}, 0x14000c0df30)
        /Users/sarahfrench/go/src/github.com/hashicorp/terraform-provider-google/google/functions/project_from_id.go:61 +0x1ec
github.com/hashicorp/terraform-provider-google/google/functions.TestFunctionRun_project_from_id.func1(0x1400105f860)
        /Users/sarahfrench/go/src/github.com/hashicorp/terraform-provider-google/google/functions/project_from_id_internal_test.go:81 +0x6c
testing.tRunner(0x1400105f860, 0x1400108c730)
        /Users/sarahfrench/sdk/go1.20.12/src/testing/testing.go:1576 +0x10c
created by testing.(*T).Run
        /Users/sarahfrench/sdk/go1.20.12/src/testing/testing.go:1629 +0x368
```

and I can address the problem by updating my test to include this:

```go
got := function.RunResponse{
	Result: function.NewResultData(basetypes.StringValue{}), // Required to avoid nil pointer error
}
```

**Comment by bflad** [comment]
Hi @SarahFrench 👋 Thank you for reporting this and sorry you ran into trouble here.

It looks like [that documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions/testing#unit-testing) is specifying the `function.RunResponse.Result` for the test cases but not the `got` variable. If you are interested in submitting a documentation fix for that variable declaration to include the `Result`, we would be happy to accept it.

Cheers!
