### ISSUE TITLE
Panic with Computed MapNestedAttributes

### ISSUE THREAD

**Issue by FlorianJDF** [hashicorp/terraform-plugin-framework#98]
### Module version

```
github.com/hashicorp/terraform-plugin-framework v0.2.0
```

### Relevant provider source code

```go
type resourceXXXType struct{}

func (resourceType resourceXXXType) GetSchema(_ context.Context) (schema.Schema, []*tfprotov6.Diagnostic) {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": {
				Type:     types.StringType,
				Computed: true,
			},
			"name": {
				Type:     types.StringType,
				Required: true,
			},
			"resources": {
				Computed: true,
				Attributes: schema.MapNestedAttributes(map[string]schema.Attribute{
					"id": {
						Type:     types.StringType,
						Computed: true,
					},
				}, schema.MapNestedAttributesOptions{}),
			},
		},
	}, nil
}
```

### Debug Output

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

panic: value is not known

goroutine 26 [running]:
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2b43420, 0xc0009dbcd0, 0x2313a60, 0x3be0600, 0x0)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.9.0/cty/value_ops.go:1060 +0x2a7
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x2b43420, 0xc0009dbcd0, 0x2313a60, 0x3be0600, 0x0)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.9.0/cty/value_ops.go:1320 +0x9d
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeNestedAttrDiff(0xc000289768, 0xc0009dc330, 0xd, 0xc000b3b8a0, 0x2b43420, 0xc0009dbcd0, 0x0, 0x0, 0x2b43420, 0xc0009dbcd0, ...)
        /home/circleci/project/project/internal/command/format/diff.go:669 +0x13ee
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc000289768, 0xc0009dc330, 0xd, 0xc0009e4b40, 0x2b43420, 0xc0009dbcd0, 0x0, 0x0, 0x2b43420, 0xc0009dbcd0, ...)
        /home/circleci/project/project/internal/command/format/diff.go:473 +0x7a7
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeAttrsDiff(0xc000289768, 0xc0009e97d0, 0x2b43458, 0xc000bc97c0, 0x0, 0x0, 0x2b43458, 0xc000bc99d0, 0x233d560, 0xc0000c2d20, ...)
        /home/circleci/project/project/internal/command/format/diff.go:434 +0x685
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc000289768, 0xc0009e9830, 0x2b43458, 0xc000bc97c0, 0x0, 0x0, 0x2b43458, 0xc000bc99d0, 0x233d560, 0xc0000c2d20, ...)
        /home/circleci/project/project/internal/command/format/diff.go:358 +0x12f
github.com/hashicorp/terraform/internal/command/format.ResourceChange(0xc00015cf20, 0xc0009e9830, 0xc0002d6850, 0xf, 0xc00045e228)
        /home/circleci/project/project/internal/command/format/diff.go:132 +0x665
github.com/hashicorp/terraform/internal/command/views.renderPlan(0xc000bde140, 0xc000bcb9e0, 0xc0000986e0)
        /home/circleci/project/project/internal/command/views/plan.go:285 +0xafe
github.com/hashicorp/terraform/internal/command/views.(*OperationHuman).Plan(0xc000bcb510, 0xc000bde140, 0xc000bcb9e0)
        /home/circleci/project/project/internal/command/views/operation.go:92 +0x45
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc0009fc320, 0x2b41778, 0xc000b6ef80, 0x2b41778, 0xc000b6efc0, 0xc000bfe240, 0xc000b6ef40)
        /home/circleci/project/project/internal/backend/local/backend_plan.go:147 +0x8fc
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1(0xc000bcb550, 0xc000bcb560, 0xc000bcb570, 0xc0009fc320, 0xc000bcb540, 0x2b41778, 0xc000b6ef80, 0x2b41778, 0xc000b6efc0, 0xc000bfe240, ...)
        /home/circleci/project/project/internal/backend/local/backend.go:321 +0xe8
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:315 +0x2f2




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.993440385.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.993440385.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

### Expected Behavior

Being able to use a nested map as a computed element

### Actual Behavior

Panic when option "computed" of a nestedMap is on and a plan is started.
(PS: Same behavior with nested Set)

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by bflad** [comment]
Hi @FlorianJDF 👋  Thank you for raising this and sorry you ran into trouble with this functionality.

An interesting thing to notice in this stacktrace is that it seems to be arising between the interaction of https://github.com/hashicorp/terraform and https://github.com/zclconf/go-cty. While its entirely possible this is being caused by this project, it may also warrant filing an issue upstream in https://github.com/hashicorp/terraform to potentially raise an error message in this situation (or otherwise handle it better) rather than panicking.

That being said, would it be possible to send along the code you are using to set the value of the `resources` attribute and what configuration caused this? That extra information might prove to be very helpful on both sides of this for further triage.

Thanks so much. 👍

**Comment by FlorianJDF** [comment]
Hi @bflad, thank you for your answer

All my functions Read, Create, Update, and Delete are empty (just so you know).

Here is the .tf that I'm using:
```terraform
terraform {
  required_version = ">= 1.0"
  required_providers {
    ptest = {
      source = "xxxxxxx/xxxxxxxxx/xxxxxxxxxx"
      version = "2.0.0"
    }
  }
}

resource "t_component" "base-config" {
  name             = "base-config"
}

```

The additionnal code of my resource:
```go
func (resourceType resourceXXXType) NewResource(_ context.Context, provider tfsdk.Provider) (tfsdk.Resource, []*tfprotov6.Diagnostic) {
	return resourceXXX{
		provider: *(provider.(*xxxProvider)),
	}, nil
}

type resourceXXX struct {
	provider xxxProvider
}
```

If you need any more information i'll happy to provide them

**Comment by bflad** [comment]
> All my functions Read, Create, Update, and Delete are empty

Ah ha -- that might actually be the cause here. I believe our plans are for this framework to surface issues like this, but for now I think any attributes must be set in the state before returning back to Terraform CLI during CRU operations. My hunch is that returning an entirely empty state (at least in the way that this framework is currently written) is confusing Terraform CLI's plan difference handling to ultimately cause the panic. Does it work better if you implement calls to `resp.State.Set(ctx, /* your type here */)` in Create, Read, and Update? A quick example can be found over here: https://github.com/hashicorp/tfsdkdemo-provider-hashitalks/blob/main/internal/provider/resource_speaker.go

**Comment by FlorianJDF** [comment]
The thing is that I put some logs in the Read function and noting is showing up on the logs,
so I understood that the Read was not call at the first plan (like the SDK).

But it is failing during the first plan (nothing in the statefile at this point).

And if I remove this fields as Computed (put optionnal for exemple), or change the type to SingleNestedAttribute,
the plan is a success and terraform tells me that my resource will be created.

I'll try to make a full example and paste it here

**Comment by FlorianJDF** [comment]
Hi @bflad 

I broke it down to the bare minimum with some data in the Create, Read Update.
Still the same Panic after just the first Plan.

Maybe I'm missing something.

Here is all the code.

main.go
```go
package main

import (
	"context"

	t1000 "github.com/FlorianJDF/t1000-provider/t1000"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
)

func main() {
	tfsdk.Serve(
		context.Background(),
		t1000.New,
		tfsdk.ServeOpts{
			Name: "t1000",
		})
}
```

provider.go
```go
package moprh

import (
	"context"
	"os"

	"github.com/hashicorp/terraform-plugin-framework/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
)

var stderr = os.Stderr

func New() tfsdk.Provider {
	return &t1000Provider{}
}

type t1000Provider struct {
	configured bool
	client     *T1000Client
}

type T1000Client struct {
	name string
}

func (p *t1000Provider) GetSchema(_ context.Context) (schema.Schema, []*tfprotov6.Diagnostic) {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"pname": {
				Type:     types.StringType,
				Required: true,
			},
		},
	}, nil
}

type providerData struct {
	Pname types.String `tfsdk:"pname"`
}

func (p *t1000Provider) Configure(ctx context.Context, providerRequest tfsdk.ConfigureProviderRequest, providerResponse *tfsdk.ConfigureProviderResponse) {
	var providerConfiguration providerData

	err := providerRequest.Config.Get(ctx, &providerConfiguration)
	if err != nil {
		providerResponse.Diagnostics = append(providerResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error parsing Provider configuration",
			Detail:   "Error parsing Provider configuration. This is an error with the provider. Please report the error:\n" + err.Error(),
		})
		return
	}

	p.client = &T1000Client{
		name: providerConfiguration.Pname.Value,
	}
	if err != nil {
		providerResponse.Diagnostics = append(providerResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error configuring Provider",
			Detail:   "Error configuring Provider:\n" + err.Error(),
		})
		return
	}

	p.configured = true
}

func (p *t1000Provider) GetResources(_ context.Context) (map[string]tfsdk.ResourceType, []*tfprotov6.Diagnostic) {
	return map[string]tfsdk.ResourceType{
		"t1000_component": resourceComponentType{},
	}, nil
}

func (p *t1000Provider) GetDataSources(_ context.Context) (map[string]tfsdk.DataSourceType, []*tfprotov6.Diagnostic) {
	return map[string]tfsdk.DataSourceType{}, nil
}

```

resource
```go
package moprh

import (
	"context"
	"log"

	"github.com/hashicorp/terraform-plugin-framework/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
)

type resourceComponentType struct{}

func (resourceType resourceComponentType) GetSchema(_ context.Context) (schema.Schema, []*tfprotov6.Diagnostic) {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": {
				Type:     types.StringType,
				Computed: true,
			},

			"name": {
				Type:     types.StringType,
				Required: true,
			},
			"resources": {
				Computed: true,
				Attributes: schema.MapNestedAttributes(map[string]schema.Attribute{
					"name": {
						Type:     types.StringType,
						Computed: true,
					},
				}, schema.MapNestedAttributesOptions{}),
			},
		},
	}, nil
}

func (resourceType resourceComponentType) NewResource(_ context.Context, provider tfsdk.Provider) (tfsdk.Resource, []*tfprotov6.Diagnostic) {
	return resourceT1000{
		provider: *(provider.(*t1000Provider)),
	}, nil
}

type resourceT1000 struct {
	provider t1000Provider
}

func (resource resourceT1000) Create(ctx context.Context, resourceRequest tfsdk.CreateResourceRequest, resourceResponse *tfsdk.CreateResourceResponse) {
	var planResult t1000Component

	err := resourceRequest.Plan.Get(ctx, &planResult)
	if err != nil {
		resourceResponse.Diagnostics = append(resourceResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error reading plan",
			Detail:   "An unexpected error was encountered while reading the plan: " + err.Error(),
		})
		return
	}

	log.Println("[T1000] IN CREATE")

	var resourceResult = t1000Component{
		ID:   types.String{Value: "1"},
		Name: planResult.Name,
		Resources: map[string]Resource{
			"1": {
				Name: types.String{Value: "test"},
			},
		},
	}

	err = resourceResponse.State.Set(ctx, resourceResult)
	if err != nil {
		resourceResponse.Diagnostics = append(resourceResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error setting state",
			Detail:   "Could not set state, unexpected error: " + err.Error(),
		})
		return
	}
}

func (resource resourceT1000) Read(ctx context.Context, resourceRequest tfsdk.ReadResourceRequest, resourceResponse *tfsdk.ReadResourceResponse) {
	var componentState t1000Component
	err := resourceRequest.State.Get(ctx, &componentState)
	if err != nil {
		resourceResponse.Diagnostics = append(resourceResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error reading state",
			Detail:   "An unexpected error was encountered while reading the state: " + err.Error(),
		})
		return
	}

	log.Println("[T1000] IN READ")

	componentState.Resources = map[string]Resource{
		"1": {
			Name: types.String{
				Value: "test2",
			},
		},
	}

	err = resourceResponse.State.Set(ctx, componentState)
	if err != nil {
		resourceResponse.Diagnostics = append(resourceResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error setting state",
			Detail:   "An unexpected error was encountered while setting the state: " + err.Error(),
		})
		return
	}
}

func (resource resourceT1000) Update(ctx context.Context, resourceRequest tfsdk.UpdateResourceRequest, resourceResponse *tfsdk.UpdateResourceResponse) {
	var componentState t1000Component
	err := resourceRequest.State.Get(ctx, &componentState)
	if err != nil {
		resourceResponse.Diagnostics = append(resourceResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error reading state",
			Detail:   "An unexpected error was encountered while reading the state: " + err.Error(),
		})
		return
	}

	log.Println("[T1000] IN UPDATE")

	componentState.Resources = map[string]Resource{
		"1": {
			Name: types.String{
				Value: "test2",
			},
		},
	}

	err = resourceResponse.State.Set(ctx, componentState)
	if err != nil {
		resourceResponse.Diagnostics = append(resourceResponse.Diagnostics, &tfprotov6.Diagnostic{
			Severity: tfprotov6.DiagnosticSeverityError,
			Summary:  "Error setting state",
			Detail:   "An unexpected error was encountered while setting the state: " + err.Error(),
		})
		return
	}
}

func (resource resourceT1000) Delete(ctx context.Context, resourceRequest tfsdk.DeleteResourceRequest, resourceResponse *tfsdk.DeleteResourceResponse) {
}

type t1000Component struct {
	ID        types.String        `tfsdk:"id"`
	Name      types.String        `tfsdk:"name"`
	Resources map[string]Resource `tfsdk:"ocp_resources"`
}

type Resource struct {
	Name types.String `tfsdk:"name"`
}

```

main.tf
```terraform
terraform {
  required_version = ">= 1.0"
  required_providers {
    t1000 = {
      source = "test/jdf/t1000"
      version = "2.0.0"
    }
  }
}


provider "t1000" {
  pname   = "test"
}

resource "t1000_component" "base-config" {
  name             = "base-config"
}
```


logs
```bash
$> tf init

Initializing the backend...

Initializing provider plugins...
- Finding test/jdf/t1000 versions matching "2.0.0"...
- Installing test/jdf/t1000 v2.0.0...
- Installed test/jdf/t1000 v2.0.0 (unauthenticated)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$> tf plan

Terraform used the selected providers to generate the following execution plan. Resource actions
are indicated with the following symbols:
  + create

Terraform will perform the following actions:

panic: value is not known

goroutine 20 [running]:
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2b43420, 0xc000a9f000, 0x2313a60, 0x3be0600, 0x0)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.9.0/cty/value_ops.go:1060 +0x2a7
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x2b43420, 0xc000a9f000, 0x2313a60, 0x3be0600, 0x0)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.9.0/cty/value_ops.go:1320 +0x9d
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeNestedAttrDiff(0xc0009d3768, 0xc000ac45b0, 0x9, 0xc000a92500, 0x2b43420, 0xc000a9f000, 0x0, 0x0, 0x2b43420, 0xc000a9f000, ...)
        /home/circleci/project/project/internal/command/format/diff.go:669 +0x13ee
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc0009d3768, 0xc000ac45b0, 0x9, 0xc0008b8e80, 0x2b43420, 0xc000a9f000, 0x0, 0x0, 0x2b43420, 0xc000a9f000, ...)
        /home/circleci/project/project/internal/command/format/diff.go:473 +0x7a7
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeAttrsDiff(0xc0009d3768, 0xc000b48de0, 0x2b43458, 0xc000afcf80, 0x0, 0x0, 0x2b43458, 0xc000afd070, 0x233d560, 0xc000a4d4d0, ...)
        /home/circleci/project/project/internal/command/format/diff.go:434 +0x685
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc0009d3768, 0xc000b48e40, 0x2b43458, 0xc000afcf80, 0x0, 0x0, 0x2b43458, 0xc000afd070, 0x233d560, 0xc000a4d4d0, ...)
        /home/circleci/project/project/internal/command/format/diff.go:358 +0x12f
github.com/hashicorp/terraform/internal/command/format.ResourceChange(0xc0006f0c60, 0xc000b48e40, 0xc000680940, 0xf, 0xc000347a88)
        /home/circleci/project/project/internal/command/format/diff.go:132 +0x665
github.com/hashicorp/terraform/internal/command/views.renderPlan(0xc0000e9cc0, 0xc000367000, 0xc000528620)
        /home/circleci/project/project/internal/command/views/plan.go:285 +0xafe
github.com/hashicorp/terraform/internal/command/views.(*OperationHuman).Plan(0xc000366170, 0xc0000e9cc0, 0xc000367000)
        /home/circleci/project/project/internal/command/views/operation.go:92 +0x45
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc0000e8780, 0x2b41778, 0xc0008b8380, 0x2b41778, 0xc0008b83c0, 0xc000648fc0, 0xc0008b8340)
        /home/circleci/project/project/internal/backend/local/backend_plan.go:147 +0x8fc
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1(0xc0003662b0, 0xc0003662e0, 0xc000366310, 0xc0000e8780, 0xc000366280, 0x2b41778, 0xc0008b8380, 0x2b41778, 0xc0008b83c0, 0xc000648fc0, ...)
        /home/circleci/project/project/internal/backend/local/backend.go:321 +0xe8
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:315 +0x2f2




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.815119339.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.815119339.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by paddycarver** [comment]
I'm pretty sure this is hashicorp/terraform#29205. Using terraform v1.0.3 and later should resolve this. I know the readme says Terraform 0.15 and higher right now, but it's actually Terraform 1.0.3 and higher. I've opened #101 to correct that.

**Comment by FlorianJDF** [comment]
Hello @paddycarver ,

I am on terraform 1.0.4

```bash
$> tf version; tf init; tf plan -out chain
Terraform v1.0.4
on linux_amd64

Initializing the backend...

Initializing provider plugins...
- Finding test/jdf/t1000 versions matching "2.0.0"...
- Installing test/jfd/t1000 v2.0.0...
- Installed test/jfd/t1000 v2.0.0 (unauthenticated)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

panic: value is not known

goroutine 12 [running]:
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2b43420, 0xc000a3d970, 0x2313a60, 0x3be0600, 0x0)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.9.0/cty/value_ops.go:1060 +0x2a7
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x2b43420, 0xc000a3d970, 0x2313a60, 0x3be0600, 0x0)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.9.0/cty/value_ops.go:1320 +0x9d
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeNestedAttrDiff(0xc00034b768, 0xc0003fc5d0, 0x9, 0xc00094a380, 0x2b43420, 0xc000a3d970, 0x0, 0x0, 0x2b43420, 0xc000a3d970, ...)
        /home/circleci/project/project/internal/command/format/diff.go:669 +0x13ee
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeAttrDiff(0xc00034b768, 0xc0003fc5d0, 0x9, 0xc0006f6780, 0x2b43420, 0xc000a3d970, 0x0, 0x0, 0x2b43420, 0xc000a3d970, ...)
        /home/circleci/project/project/internal/command/format/diff.go:473 +0x7a7
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeAttrsDiff(0xc00034b768, 0xc0006fa720, 0x2b43458, 0xc000a3d610, 0x0, 0x0, 0x2b43458, 0xc000a3d700, 0x233d560, 0xc000629b30, ...)
        /home/circleci/project/project/internal/command/format/diff.go:434 +0x685
github.com/hashicorp/terraform/internal/command/format.(*blockBodyDiffPrinter).writeBlockBodyDiff(0xc00034b768, 0xc0006fa780, 0x2b43458, 0xc000a3d610, 0x0, 0x0, 0x2b43458, 0xc000a3d700, 0x233d560, 0xc000629b30, ...)
        /home/circleci/project/project/internal/command/format/diff.go:358 +0x12f
github.com/hashicorp/terraform/internal/command/format.ResourceChange(0xc000141080, 0xc0006fa780, 0xc00062a970, 0xf, 0xc0001ad8e8)
        /home/circleci/project/project/internal/command/format/diff.go:132 +0x665
github.com/hashicorp/terraform/internal/command/views.renderPlan(0xc0006cc460, 0xc00032bb40, 0xc000400d40)
        /home/circleci/project/project/internal/command/views/plan.go:285 +0xafe
github.com/hashicorp/terraform/internal/command/views.(*OperationHuman).Plan(0xc00032b6a0, 0xc0006cc460, 0xc00032bb40)
        /home/circleci/project/project/internal/command/views/operation.go:92 +0x45
github.com/hashicorp/terraform/internal/backend/local.(*Local).opPlan(0xc000437cc0, 0x2b41778, 0xc000433a40, 0x2b41778, 0xc000433a80, 0xc0006186c0, 0xc000433a00)
        /home/circleci/project/project/internal/backend/local/backend_plan.go:147 +0x8fc
github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation.func1(0xc00032b6e0, 0xc00032b6f0, 0xc00032b700, 0xc000437cc0, 0xc00032b6d0, 0x2b41778, 0xc000433a40, 0x2b41778, 0xc000433a80, 0xc0006186c0, ...)
        /home/circleci/project/project/internal/backend/local/backend.go:321 +0xe8
created by github.com/hashicorp/terraform/internal/backend/local.(*Local).Operation
        /home/circleci/project/project/internal/backend/local/backend.go:315 +0x2f2




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.864746720.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.864746720.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by paddycarver** [comment]
Ah! My mistake, sorry. We may have encountered another core bug here. I'm going to send this over to the hashicorp/terraform repo, because it looks like the panic is coming from Terraform, not the SDK.
